project_id = "yyypaywmjowbicammdnp"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.manage-admin-users]
    verify_jwt = false
  [functions.submit-assessment]
    verify_jwt = false
  [functions.update-silver-price]
    verify_jwt = false
  [functions.update-user-email]
    verify_jwt = false
  [functions.update-user-profile]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = false
  [functions.stripe-webhook]
    verify_jwt = false
  [functions.send-transactional-email]
    verify_jwt = false
  [functions.ghl-sync]
    verify_jwt = false
  [functions.ghl-backfill]
    verify_jwt = false
